"""More tips for the 🐧 Linux 主机 category (Ubuntu Server 24.04). Written for this site.
Each tip: (title, what it is for, [steps], note or "")."""

MORE = [
    # ---- 文件和目录 ----
    ("ls -lah：把文件看清楚", "看到隐藏文件、大小和权限",
     ["ls -lah：l 是详细列表，a 显示 . 开头的隐藏文件，h 把大小写成 K/M/G",
      "第一列像 -rwxr-xr-x 的是权限，d 开头的是文件夹",
      "ls -lt 按修改时间排序，最新改过的在最上面"],
     ""),
    ("cd 的几个快捷写法", "在目录之间跳来跳去不迷路",
     ["cd 后面什么都不加：回到自己的家目录 ~",
      "cd -：回到上一次待的目录，来回切很方便",
      "cd .. 上一级；pwd 看自己现在在哪"],
     ""),
    ("tree：目录结构一目了然", "看清项目里都有哪些文件",
     ["运行：sudo apt install tree",
      "cd ~/tools，然后 tree -L 2（只看两层）",
      "不想看虚拟环境和缓存：tree -L 2 -I '.venv|__pycache__'"],
     ""),
    ("复制、移动、删除别手滑", "cp、mv、rm 的安全用法",
     ["复制文件夹要加 -r：cp -r 源文件夹 目标文件夹",
      "mv 既能移动也能改名：mv old.py new.py；加 -i 覆盖前会先问你",
      "删之前先用 ls 看一眼要删的东西，确认了再 rm；rm -i 会一个个问"],
     "rm 删掉的东西没有回收站；用 rm -rf 前务必看清路径，路径里多一个空格就可能删错地方。"),
    ("nano：直接在主机上改文件", "不会 vim 也能改配置",
     ["nano 文件名 打开（没有就新建）；改系统配置前面加 sudo",
      "Ctrl + O 再按回车 = 保存；Ctrl + X = 退出",
      "Ctrl + W 搜索，Ctrl + K 剪掉一整行，Ctrl + U 粘贴回来"],
     "屏幕底部提示里的 ^ 就是 Ctrl 键的意思。"),
    ("看长文件：less、head、tail", "日志太长，一下刷屏看不完",
     ["less 文件名：空格往下翻，b 往回翻，/关键词 搜索，q 退出",
      "head -n 20 文件 看开头 20 行；tail -n 20 文件 看最后 20 行",
      "tail -f 文件 实时盯着新写进来的内容，Ctrl + C 停止"],
     ""),
    ("数一数：wc -l 和 grep -c", "文件有几行、某个词出现几次",
     ["wc -l data.csv 看有多少行（数据条数 = 行数 - 表头）",
      "grep -c 关键词 文件 数有几行包含它",
      "接在管道后面也行：ls ~/tools | wc -l 数有几个文件"],
     ""),
    ("grep 的三个常用开关", "从一堆输出里只留想看的",
     ["-i 不分大小写：grep -i error app.log",
      "-v 反过来，去掉匹配的行：grep -v DEBUG app.log",
      "配合管道过滤日志：journalctl -u tools-web | grep -i error"],
     ""),
    ("> 和 >>：把输出存进文件", "命令结果存下来慢慢看",
     ["命令 > out.txt：写进文件（会覆盖原来的内容）",
      "命令 >> out.txt：追加到文件末尾",
      "命令 > out.txt 2>&1：连错误信息一起存",
      "| 是把前一个命令的结果交给后一个命令，比如 ls -l | less"],
     "> 会先把原文件清空，对重要文件用之前想清楚。"),
    ("ln -s：给常用目录做快捷方式", "深层目录一步就进去",
     ["ln -s /mnt/backup ~/backup",
      "以后 cd ~/backup 就直接进到移动硬盘",
      "删快捷方式：rm ~/backup（结尾不要加 /，也不要加 -r）"],
     "千万别用 rm -r ~/backup/ 删快捷方式，那会把它指向的真文件删掉。"),
    ("压缩和解压：tar 和 zip", "打包发给别人、解开下载的包",
     ["打包：tar czf 名字.tar.gz 文件夹",
      "先看里面有什么：tar tzf 名字.tar.gz；解开：tar xzf 名字.tar.gz",
      "给 Windows 用：sudo apt install zip unzip，然后 zip -r 名字.zip 文件夹，解压用 unzip 名字.zip"],
     "记法：c 创建、x 解开、t 列出、z 用 gzip 压缩、f 后面跟文件名。"),
    ("sha256sum：确认文件没传坏", "下载、拷贝后验证一模一样",
     ["sha256sum 文件名，得到一长串校验值",
      "跟官网公布的、或另一台机器上算出来的比，一样就没问题",
      "批量记录：sha256sum *.csv > sums.txt，以后 sha256sum -c sums.txt 检查"],
     ""),
    ("wget：下载大文件，断了能续", "直接下到主机，不经过手机",
     ["wget 网址 下载到当前目录",
      "断了就运行 wget -c 网址，接着上次的继续下",
      "指定保存的文件名：wget -O 名字 网址"],
     "大文件放在 tmux 里下，SSH 断开也不影响。"),

    # ---- 权限和用户 ----
    ("chmod +x：脚本直接运行", "不用每次都打 python 路径",
     ["脚本第一行写：#!/home/用户名/tools/.venv/bin/python（用虚拟环境里的 Python）",
      "运行：chmod +x job.py",
      "以后 ./job.py 就能直接跑"],
     "第一行里不能用 ~，要写完整路径。"),
    ("为什么别用 chmod 777", "权限报错时的正确做法",
     ["777 是「所有人都能读、写、执行」，任何程序都能改你的文件",
      "先看清归属：ls -l 文件，第三、四列是所有者和组",
      "一般够用的：普通文件 644，脚本和文件夹 755，密钥 600（chmod 600 ~/.ssh/id_ed25519）"],
     "chmod -R 改错了很难恢复，用 -R 之前一定确认路径。"),
    ("chown：把文件归属改回自己", "sudo 建的文件自己改不了",
     ["ls -l 看第三列，显示 root 的就是用 sudo 时建的",
      "改回来：sudo chown $USER:$USER 文件",
      "整个项目：sudo chown -R $USER:$USER ~/tools"],
     "-R 会改下面所有文件，别对 /、/etc 这种系统目录用。"),
    ("加用户、给 sudo 权限", "给家人或测试单独开个账号",
     ["sudo adduser 新用户名（按提示设密码，其他信息可以直接回车）",
      "给管理员权限：sudo usermod -aG sudo 新用户名",
      "groups 用户名 看他在哪些组；su - 新用户名 切换过去试试"],
     "-aG 里的 a 不能漏，漏了会把他原来的组都去掉。"),

    # ---- 软件包 ----
    ("apt：更新系统的正确顺序", "装软件、打补丁前先做这个",
     ["sudo apt update：只刷新软件列表，不装任何东西",
      "apt list --upgradable 看有哪些可以升级",
      "sudo apt upgrade 安装更新；sudo apt full-upgrade 会在需要时增删依赖包"],
     ""),
    ("apt search：装之前先查", "不确定软件包叫什么名字",
     ["apt search 关键词（结果太多就加 | less）",
      "apt show 包名 看说明、版本和大小",
      "装：sudo apt install 包名；卸：sudo apt remove 包名"],
     ""),
    ("清理旧内核和没用的包", "/boot 满了或者想省点空间",
     ["sudo apt autoremove --purge 删掉不再需要的依赖和旧内核",
      "sudo apt clean 清掉下载过的安装包缓存",
      "uname -r 看正在用的内核，它不会被删"],
     ""),
    ("apt 说有包 kept back", "有更新但就是不装",
     ["Ubuntu 会分批推送更新，kept back 多半是还没轮到你，过几天再 upgrade 通常就好了",
      "apt-mark showhold 看有没有被手动锁住的包",
      "想锁住某个包不升级：sudo apt-mark hold 包名；解锁：sudo apt-mark unhold 包名"],
     ""),
    ("apt 提示锁被占用", "另一个程序正在用 apt",
     ["多半是自动更新在后台跑，等几分钟再试",
      "看看是谁：ps aux | grep -i apt",
      "等它结束后再装你的软件"],
     "别去删 lock 文件，强行打断可能把软件包数据库弄坏。"),
    ("snap 软件要注意的地方", "和 apt 不是一回事",
     ["snap list 看哪些软件是 snap 装的",
      "df 和 lsblk 里一堆 /dev/loop 就是 snap，不用管",
      "snap 会自己在后台更新；sudo snap refresh --hold 可以暂停自动更新",
      "同一个软件别 apt 和 snap 各装一份，容易搞不清用的是哪个"],
     ""),

    # ---- 硬盘 ----
    ("lsblk：看接了哪些硬盘", "插了 U 盘却找不到",
     ["lsblk -f 列出所有硬盘、分区、格式和挂载位置",
      "新插的 U 盘一般叫 sdb，分区叫 sdb1",
      "插拔时运行 sudo dmesg -w 能实时看到系统认出了什么，Ctrl + C 退出"],
     ""),
    ("手动挂载 U 盘或移动硬盘", "Server 版插上不会自动出现",
     ["sudo mkdir -p /mnt/usb",
      "sudo mount /dev/sdb1 /mnt/usb（名字按 lsblk 看到的写）",
      "用完先 sudo umount /mnt/usb，再拔"],
     "不先 umount 就拔可能丢数据；FAT/exFAT 格式想自己能写，挂载时加 -o uid=$(id -u),gid=$(id -g)。"),
    ("开机自动挂载备份硬盘", "备份盘一直插着用",
     ["sudo blkid 记下那个分区的 UUID 和格式（TYPE），再 sudo mkdir -p /mnt/backup",
      "先备份：sudo cp /etc/fstab /etc/fstab.bak",
      "sudo nano /etc/fstab，最后加一行：UUID=你的UUID /mnt/backup ext4 defaults,nofail 0 2（ext4 换成你的格式）",
      "sudo systemctl daemon-reload，再 sudo mount -a，没报错再重启"],
     "fstab 写错可能导致开不了机，所以一定要加 nofail，并先用 mount -a 测试。"),
    ("ncdu：一层层找大文件", "比 du 好用的空间查看器",
     ["sudo apt install ncdu",
      "ncdu ~ 扫描家目录；看整个系统：sudo ncdu -x /",
      "方向键进出文件夹，按 d 删除（会先确认），q 退出"],
     "按 d 是真删，没有回收站，别手快。"),
    ("留意固态硬盘写了多少", "估算 SSD 还能用多久",
     ["sudo smartctl -a /dev/nvme0 | grep -i -E 'written|used'",
      "「Data Units Written」后面方括号里是总写入量，「Percentage Used」是磨损百分比",
      "写得太快就找元凶：sudo apt install iotop，然后 sudo iotop -o",
      "systemctl status fstrim.timer 确认每周 TRIM 是开着的"],
     ""),

    # ---- 内存和进程 ----
    ("内存「快用完」先别慌", "Linux 喜欢拿空闲内存做缓存",
     ["free -h 主要看 available 那一列，不是 free",
      "buff/cache 是缓存，程序需要时会自动让出来",
      "available 很少、swap 用量一直在涨，才是真的不够"],
     ""),
    ("给主机加一个 swap 文件", "内存小、程序总被系统杀掉",
     ["先看已有的：swapon --show（装系统时一般已经建了 /swap.img）",
      "sudo fallocate -l 4G /swapfile && sudo chmod 600 /swapfile",
      "sudo mkswap /swapfile && sudo swapon /swapfile",
      "开机自动启用：echo '/swapfile none swap sw 0 0' | sudo tee -a /etc/fstab"],
     "swap 只是救急，比内存慢很多，常年用很多 swap 就该考虑加内存。"),
    ("程序突然死了？查 OOM", "看是不是内存不够被系统杀掉",
     ["journalctl -k | grep -i -E 'out of memory|killed process'",
      "里面出现你的 python 进程，就是被系统杀了",
      "办法：加 swap、一次少读点数据，或在服务的 [Service] 里写 MemoryMax=1G 防止拖垮整台机器"],
     ""),
    ("找到某个程序的 PID", "想结束它、看它在不在跑",
     ["ps aux | grep python 列出所有 python 进程",
      "每行第二列就是 PID",
      "更简洁：pgrep -af python"],
     ""),
    ("kill：结束卡住的程序", "Ctrl + C 停不下来的时候",
     ["kill PID：礼貌地让它退出",
      "等几秒还在：kill -9 PID 强制结束",
      "按名字结束：pkill -f job.py"],
     "systemd 管的服务别用 kill，用 sudo systemctl stop 服务名，否则它可能被自动拉起来。"),
    ("按了 Ctrl + Z 程序去哪了", "不小心把程序挂起了",
     ["Ctrl + Z 是暂停并放到后台，不是退出",
      "jobs 看有哪些被挂起的任务",
      "fg 拿回前台继续；想结束就 fg 之后按 Ctrl + C"],
     ""),
    ("nice：大任务别抢资源", "跑数据时网站不卡",
     ["nice -n 10 python job.py：用低优先级运行",
      "已经在跑的：sudo renice -n 10 -p PID",
      "数字越大越「谦让」，范围是 -20 到 19"],
     "systemd 服务可以直接在 [Service] 里写 Nice=10。"),

    # ---- 网络 ----
    ("看 IP、查网通不通", "连不上时先查这三样",
     ["ip -br a 简洁列出每个网卡和 IP（tailscale0 是 Tailscale 的）",
      "ping -c 4 1.1.1.1 测外网；ping -c 4 google.com 再测域名",
      "ip route 看默认网关（一般就是路由器）"],
     "IP 能 ping 通、域名不通，就是 DNS 的问题。"),
    ("域名解析出问题怎么查", "ping 得通 IP，打不开网址",
     ["resolvectl status 看用的是哪个 DNS 服务器",
      "resolvectl query google.com 测试解析",
      "用 dig 看更详细：dig google.com +short（没有 dig 就 sudo apt install bind9-dnsutils）"],
     "开了 Tailscale 的 MagicDNS 后，DNS 里出现 100.100.100.100 是正常的。"),
    ("curl：测网站还活着吗", "网页打不开时分清是谁的问题",
     ["在主机上：curl -I http://localhost:端口，看到 200 就说明程序正常",
      "看返回内容开头：curl -s 网址 | head",
      "加 -v 看连接的全过程"],
     "主机上 curl 正常、手机打不开，就去查防火墙和 Tailscale。"),
    ("测一下主机的网速", "宽带或网线是不是拖后腿",
     ["sudo apt install speedtest-cli",
      "运行 speedtest-cli，看下载、上传和延迟",
      "只要简单结果：speedtest-cli --simple"],
     ""),
    ("给主机固定局域网 IP", "IP 变了就找不到主机",
     ["最省事：在路由器后台给主机的 MAC 地址做「DHCP 保留」（也叫静态分配）",
      "MAC 地址在 ip link 里 link/ether 后面",
      "用 Tailscale 的话本来就有固定的 100.x 地址"],
     "自己改 /etc/netplan 写错可能直接断网，远程操作时别碰。"),
    ("从外面检查开了哪些端口", "确认没把不该开的暴露出去",
     ["在手机 Termux 里装：pkg install nmap",
      "扫主机的局域网地址：nmap 192.168.x.x",
      "再扫它的 Tailscale 地址对比，只该看到你想开的端口"],
     "只扫自己的设备。"),

    # ---- SSH 和传文件 ----
    ("~/.ssh/config：给主机起短名", "ssh mini 一个词就连上",
     ["在 Termux 或电脑上：nano ~/.ssh/config",
      "写四行：Host mini，HostName 主机的 Tailscale IP，User 用户名，ServerAliveInterval 30（每项一行）",
      "以后 ssh mini、scp 文件 mini:~ 都能用这个名字"],
     "ServerAliveInterval 让连接定时打个招呼，手机上不容易掉线。"),
    ("关掉 SSH 密码登录", "只认密钥，最安全",
     ["先另开一个窗口确认密钥登录没问题",
      "sudo nano /etc/ssh/sshd_config.d/00-no-password.conf，写一行：PasswordAuthentication no",
      "sudo sshd -T | grep -i passwordauth 确认显示 no",
      "sudo systemctl restart ssh"],
     "文件名用 00 开头才能排在 50-cloud-init.conf 前面生效；改之前务必确认密钥能登录，否则会把自己锁在外面。"),
    ("mosh：换网络也不掉线", "WiFi 切流量，连接照样在",
     ["主机：sudo apt install mosh",
      "Termux：pkg install mosh",
      "连接：mosh 用户名@主机地址（~/.ssh/config 里的别名也能用）"],
     "mosh 用 UDP 60000–61000 端口；ufw 已经放行 tailscale0 的话，走 Tailscale 不用另外开。"),
    ("scp：手机和主机互传文件", "传一两个文件最快",
     ["Termux 先运行一次 termux-setup-storage，允许访问手机存储",
      "从主机拿：scp mini:~/tools/data.csv ~/storage/downloads/",
      "传上去：scp ~/storage/downloads/文件 mini:~/tools/；整个文件夹加 -r"],
     ""),
    ("rsync：只传有变化的部分", "大文件夹同步，又快又能续",
     ["两边都要装：主机 sudo apt install rsync，Termux pkg install rsync",
      "从主机拉到本地：rsync -avh --progress mini:~/tools/data/ ./data/",
      "源路径结尾的 / 表示「复制里面的内容」，不加会多套一层文件夹"],
     "加 -n 是试跑，只显示会做什么、不真的传。"),

    # ---- 定时任务和日志 ----
    ("cron 时间格式怎么读", "看懂那五个星号",
     ["五个位置依次是：分 时 日 月 星期",
      "30 6 * * 1-5 = 周一到周五 6:30；*/15 * * * * = 每 15 分钟",
      "crontab -e 编辑自己的定时任务，crontab -l 查看"],
     "cron 里的命令要写完整路径，比如 /home/用户名/tools/.venv/bin/python。"),
    ("自己写一个 systemd 定时器", "比 cron 好查日志，错过能补跑",
     ["建 /etc/systemd/system/job.service：[Service] 下写 Type=oneshot、User=用户名、ExecStart=/home/用户名/tools/.venv/bin/python /home/用户名/tools/job.py",
      "建同名的 job.timer：[Timer] 下写 OnCalendar=Mon..Fri 06:30 和 Persistent=true；[Install] 下写 WantedBy=timers.target",
      "sudo systemctl daemon-reload，然后 sudo systemctl enable --now job.timer",
      "想马上测一次：sudo systemctl start job.service"],
     "Persistent=true 表示关机错过的那次会在开机后补跑；时间写法可以用 systemd-analyze calendar 'Mon..Fri 06:30' 检查。"),
    ("定时任务失败自动推送", "任务挂了第一时间知道",
     ["建 /etc/systemd/system/notify-fail@.service：[Service] 下写 Type=oneshot 和 ExecStart=/usr/bin/curl -d \"%i 失败了\" ntfy.sh/你的主题",
      "在任务的 .service 文件 [Unit] 下加一行：OnFailure=notify-fail@%n.service",
      "sudo systemctl daemon-reload",
      "测试推送：sudo systemctl start notify-fail@test.service"],
     "自建的 ntfy 就把 ntfy.sh 换成你自己的地址。"),
    ("命令跑完推送到手机", "长任务结束自动提醒",
     ["curl -d \"备份完成\" ntfy.sh/你的主题",
      "接在命令后面：python job.py && curl -d '成功' ntfy.sh/主题 || curl -d '失败了' ntfy.sh/主题",
      "手机 ntfy App 里订阅同一个主题名"],
     "公共 ntfy.sh 谁猜到主题名谁就能看，名字起长一点，别发敏感内容。"),
    ("开机自动跑一个脚本", "主机重启后自动执行",
     ["跑一次就完的：crontab -e，加一行 @reboot /home/用户名/tools/.venv/bin/python /home/用户名/tools/start.py",
      "要一直运行、挂了自动重启的：写成 systemd 服务，[Service] 里加 Restart=on-failure",
      "服务写好后 sudo systemctl enable --now 服务名"],
     "@reboot 运行时网络可能还没准备好，脚本里最好等几秒或者失败重试。"),
    ("一条命令看哪些服务坏了", "开机后检查一切正常",
     ["systemctl --failed 列出启动失败的服务",
      "systemctl status 服务名 看失败原因",
      "修好后 sudo systemctl reset-failed 清掉记录"],
     ""),
    ("只看错误、看上次开机的日志", "不知道哪出问题时缩小范围",
     ["journalctl -b -p err 只看本次开机以来的错误",
      "journalctl -b -1 看上一次开机的日志（死机重启后查原因）",
      "journalctl --since \"1 hour ago\" 看最近一小时"],
     ""),
    ("给系统日志设个上限", "日志不会悄悄吃满硬盘",
     ["sudo mkdir -p /etc/systemd/journald.conf.d",
      "sudo nano /etc/systemd/journald.conf.d/size.conf，写两行：[Journal] 和 SystemMaxUse=500M",
      "sudo systemctl restart systemd-journald",
      "journalctl --disk-usage 看现在占了多少"],
     ""),
    ("logrotate：自己的日志自动切", "写进文件的日志不会无限长",
     ["新建 /etc/logrotate.d/tools，第一行写：/home/用户名/tools/logs/*.log {",
      "里面每行一个：su 用户名 用户名、weekly、rotate 4、compress、missingok、notifempty、copytruncate，最后一行写 }",
      "试跑看看：sudo logrotate -d /etc/logrotate.d/tools",
      "之后系统每天自动执行，不用自己加定时任务"],
     "用 print 输出、交给 systemd 管的程序，日志在 journal 里，不需要这个。"),

    # ---- Python 和环境 ----
    ("Python 虚拟环境：进入和退出", "装的包不会弄乱系统",
     ["source ~/tools/.venv/bin/activate，提示符前面会出现 (.venv)",
      "离开：deactivate",
      "不激活也能用：~/tools/.venv/bin/python 脚本.py",
      "重建虚拟环境：python3 -m venv ~/tools/.venv（报错就先 sudo apt install python3-venv）"],
     ""),
    ("pip 报错不让装包", "24.04 不让往系统里装包",
     ["这是故意的：别用 sudo pip，也别加 --break-system-packages",
      "先激活虚拟环境，再 pip install 包名",
      "存一份清单：pip freeze > requirements.txt；换机器 pip install -r requirements.txt"],
     "单独的命令行工具可以 sudo apt install pipx，再 pipx install 工具名。"),
    ("环境变量：密钥别写进代码", "API key 不进 git",
     ["临时设：export NTFY_TOPIC=xxx；echo $NTFY_TOPIC 查看",
      "Python 里读：os.environ.get(\"NTFY_TOPIC\")",
      "给服务用：[Service] 里写 EnvironmentFile=/home/用户名/tools/.env，然后 chmod 600 ~/tools/.env"],
     "export 只在当前窗口有效，systemd 服务也不会读你的 .bashrc。"),
    ("在 .bashrc 里加快捷命令", "常用长命令缩成一个词",
     ["nano ~/.bashrc，在最后加：alias logs='journalctl -u tools-web -f'",
      "再加一行：alias act='source ~/tools/.venv/bin/activate'",
      "保存后运行 source ~/.bashrc 立刻生效"],
     ""),
    ("which：这个命令是哪来的", "python 版本不对的时候",
     ["which python3 看实际运行的是哪个文件",
      "激活虚拟环境后再看，会变成 ~/tools/.venv/bin/python3",
      "type 命令名 还能看出它是不是你设的 alias"],
     ""),

    # ---- 安全 ----
    ("ufw：只让 Tailscale 访问", "网站和 SSH 不对外开放",
     ["放行 Tailscale 网卡：sudo ufw allow in on tailscale0",
      "留个家里的后门：sudo ufw allow from 192.168.1.0/24 to any port 22 proto tcp（按你家网段改）",
      "另开窗口确认用 Tailscale 能连上后，再删普通规则：sudo ufw delete allow OpenSSH",
      "sudo ufw status verbose 检查"],
     "删 SSH 规则前一定先测试别的连法能进，否则只能接显示器去救。"),
    ("fail2ban：自动封暴力破解", "有人狂试 SSH 密码时",
     ["sudo apt install fail2ban",
      "sudo nano /etc/fail2ban/jail.local，写：[sshd]、enabled = true、maxretry = 5、bantime = 1h（每项一行）",
      "sudo systemctl restart fail2ban",
      "sudo fail2ban-client status sshd 看封了哪些 IP"],
     "SSH 只走 Tailscale、不对公网开放的话，它不是必需的。"),
    ("看谁登录过这台主机", "检查有没有陌生的登录",
     ["last -n 20 看最近 20 次登录",
      "sudo lastb -n 20 看失败的登录尝试",
      "journalctl -u ssh --since today 看今天的 SSH 记录"],
     ""),

    # ---- 备份 ----
    ("tar 打包备份，名字带日期", "每次备份单独一个压缩包",
     ["tar czf ~/backup-tools-$(date +%F).tar.gz --exclude=.venv --exclude=__pycache__ -C ~ tools",
      "$(date +%F) 会变成 2026-10-02 这样的日期",
      "tar tzf 包名 | head 看看里面装了什么"],
     "虚拟环境不用备份，有 requirements.txt 随时能重建。"),
    ("rsync 备份到移动硬盘", "整个项目一条命令同步过去",
     ["先试跑：rsync -avn --delete --exclude .venv ~/tools/ /mnt/backup/tools/",
      "看清楚没问题，去掉 n 正式运行",
      "做成 systemd 定时器每天跑一次"],
     "--delete 会删掉目标里多出来的文件，源和目标写反就会删掉真数据，务必先用 -n 试。"),
    ("从备份恢复：先解到别处", "别让旧文件盖掉新文件",
     ["mkdir ~/restore && tar xzf 备份包.tar.gz -C ~/restore",
      "对比差别：diff -rq ~/restore/tools ~/tools",
      "确认后只把需要的文件 cp 回去",
      "重建虚拟环境：python3 -m venv ~/tools/.venv && ~/tools/.venv/bin/pip install -r ~/tools/requirements.txt"],
     "直接解压到原位置会覆盖同名文件。"),

    # ---- Docker（可选）----
    ("Docker：安装和最常用命令", "试别人的服务又不弄乱系统",
     ["sudo apt install docker.io docker-compose-v2",
      "免 sudo：sudo usermod -aG docker $USER，退出重新登录",
      "docker ps 看运行中的容器；docker logs -f 容器名 看日志",
      "在有 compose.yaml 的文件夹里：docker compose up -d 启动，docker compose down 停止"],
     "Docker 映射出来的端口会绕过 ufw 规则，而且 docker 组几乎等于 root 权限，要心里有数。"),

    # ---- 系统设置和硬件 ----
    ("时区和时间对不对", "定时任务时间不对时先查",
     ["timedatectl 看时间、时区，以及 System clock synchronized 是不是 yes",
      "改成洛杉矶时间：sudo timedatectl set-timezone America/Los_Angeles",
      "改完重启用到时间的服务：sudo systemctl restart tools-web"],
     "systemd 定时器的 OnCalendar 按系统时区算。"),
    ("给主机改个名字", "提示符和 Tailscale 里更好认",
     ["hostnamectl 看现在的名字",
      "sudo hostnamectl set-hostname mini",
      "sudo nano /etc/hosts，把 127.0.1.1 那一行的旧名字也改成 mini"],
     "如果重启后名字又变回去，把 /etc/cloud/cloud.cfg 里的 preserve_hostname 改成 true。"),
    ("更新后要不要重启", "看系统是不是在等你重启",
     ["cat /var/run/reboot-required，显示 System restart required 就要重启",
      "提示没有这个文件，说明不用重启",
      "cat /var/run/reboot-required.pkgs 看是哪些包要求的"],
     "挑个没有定时任务在跑的时间再 sudo reboot。"),
    ("看系统版本和硬件配置", "求助、查兼容性时用得上",
     ["cat /etc/os-release 看 Ubuntu 版本",
      "uname -r 看内核版本",
      "lscpu 看 CPU；lsblk 看硬盘；free -h 看内存"],
     "想要一页总览：sudo apt install inxi，然后 inxi -Fz（z 会隐藏 IP 等隐私信息）。"),
    ("powertop：主机更省电", "24 小时开机，电费少一点",
     ["sudo apt install powertop",
      "sudo powertop 看哪些设备、程序最耗电（Tab 切换页面，q 退出）",
      "sudo powertop --auto-tune 一键打开节能设置（重启后失效）"],
     "auto-tune 可能让 USB 设备（比如移动硬盘）休眠断开，出问题就别用它。"),
    ("Wake-on-LAN：远程叫醒主机", "关机了也能用手机开机",
     ["BIOS 里打开「Wake on LAN」（有的叫 Power On By PCI-E）",
      "主机上检查：sudo apt install ethtool，然后 sudo ethtool 网卡名 | grep Wake-on，有 g 就是开着",
      "记下 MAC 地址（ip link 里 link/ether 后面那串），用手机上的 WoL App 发唤醒包"],
     "只在同一个局域网里有效，手机要连家里 WiFi；Tailscale 叫不醒关着的机器。"),

    # ---- 命令行小技巧 ----
    ("命令行快捷键：少打一半字", "改长命令不用按半天方向键",
     ["Ctrl + A 跳到行首，Ctrl + E 跳到行尾",
      "Ctrl + U 删掉光标前的全部，Ctrl + W 删掉前一个词",
      "Ctrl + L 清屏；!$ 代表上一条命令的最后一个参数，比如 mkdir logs 之后 cd !$"],
     "Termux 屏幕上的额外按键栏里有 CTRL，先点它再按字母就行。"),
    ("history：翻翻以前做过什么", "忘了上次是怎么装的",
     ["history | tail -30 看最近 30 条",
      "history | grep apt 只看装软件的那些",
      "!行号 重新执行那一条，比如 !512"],
     "命令前面加一个空格，这条就不会记进历史（Ubuntu 默认如此）。"),
    ("Tab 键：自动补全", "长文件名、命令不用打全",
     ["打几个字母按 Tab，只有一个可能就自动补完",
      "连按两下 Tab 列出所有可能",
      "systemctl、apt 后面也能补全服务名和包名"],
     "补全不出来，多半是路径打错了，正好帮你检查。"),
    ("不会用命令？看 man 和 tldr", "忘了参数怎么写的时候",
     ["man 命令名 看完整说明（翻页和 less 一样，q 退出）",
      "命令 --help 看简短帮助",
      "只想看常用例子：sudo apt install tldr，然后 tldr tar（第一次提示没有数据就先 tldr --update）"],
     ""),
    ("watch：每隔几秒自动刷新", "盯着一个东西的变化",
     ["watch -n 2 free -h：每 2 秒刷新一次内存",
      "watch -d 'ls -l ~/tools/data'：-d 会高亮有变化的地方",
      "Ctrl + C 退出"],
     "命令里有管道 | 的话，整条用引号括起来。"),
    ("tmux 分屏：边看日志边干活", "一个窗口当两个用",
     ["在 tmux 里按 Ctrl + B 再按 %：左右分屏；Ctrl + B 再按 \"：上下分屏",
      "Ctrl + B 再按方向键，在格子之间切换",
      "Ctrl + B 再按 [ 可以往上翻看输出，按 q 退出翻页"],
     "tmux ls 看还有哪些会话在跑。"),
    ("screen：tmux 的老前辈", "别的教程里用 screen 时看得懂",
     ["没有就 sudo apt install screen",
      "screen -S job 开一个会话；Ctrl + A 再按 D 离开",
      "screen -ls 看列表；screen -r job 回来"],
     "已经习惯 tmux 就不用学它，二选一就好。"),
]
